# Generated by Django 5.1.5 on 2025-01-17 03:37

from django.db import migrations

def populate_priority_level(apps, schemmaeditor):
    level_entries = {
        "Low": "Low",
        "Medium": "Medium",
        "High": "High"
    }
    Level = apps.get_model("issues", "PriorityLevel")
    for key, value in level_entries.items():
        level_obj = Level(name=key, description=value)
        level_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_priority_level)
    ]
