# Generated by Django 5.1.5 on 2025-01-17 02:20

from django.db import migrations

def populate_roles(apps, schemaeditor):
    roles_entries = {
        "Developer": "The person on the team who works on issues",
        "Scrum Master": "The Coach",
        "Product Owner": "The team member in charge of defining product scope"
    }
    
    Role=apps.get_model("accounts", "Role")
    for key, value in roles_entries.items():
        roles_obj=Role(name=key, description=value)
        roles_obj.save()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles)
    ]
