# Generated by Django 5.1.5 on 2025-01-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250116_2000'),
        ('accounts', '0003_auto_20250116_2020'),
    ]

    operations = [
    ]
